### PR TITLE
added the functionality for `CREATE TABLE`

### PR DESCRIPTION
**Pull request by jatin510**
Added the `Create Table` functionality.

It does not store the table in persistence yet.

### CODE REVIEW

**Comment by penberg** [comment]
@jatin510 Nice! We want to do writes to a WAL so persistence can come later when we have it.

**Comment by jatin510** [comment]
Can we merge this **PR?**
Can we create a separate PR for the WAL support, as we don't have WAL implementation right now ?

**Comment by penberg** [comment]
The `get_next_available_page()` thing won't work so at least that ought to be dropped.

If you look at what SQLite does for `CREATE TABLE`:

```
sqlite> EXPLAIN CREATE TABLE users (id INT);
addr  opcode         p1    p2    p3    p4             p5  comment
----  -------------  ----  ----  ----  -------------  --  -------------
0     Init           0     28    0                    0   Start at 28
1     ReadCookie     0     3     2                    0
2     If             3     5     0                    0
3     SetCookie      0     2     4                    0
4     SetCookie      0     5     1                    0
5     CreateBtree    0     2     1                    0   r[2]=root iDb=0 flags=1
6     OpenWrite      0     1     0     5              0   root=1 iDb=0
7     NewRowid       0     1     0                    0   r[1]=rowid
8     Blob           6     3     0                   0   r[3]= (len=6)
9     Insert         0     3     1                    8   intkey=r[1] data=r[3]
10    Close          0     0     0                    0
11    Close          0     0     0                    0
12    Null           0     4     5                    0   r[4..5]=NULL
13    Noop           2     0     4                    0
14    OpenWrite      1     1     0     5              0   root=1 iDb=0; sqlite_master
15    SeekRowid      1     17    1                    0   intkey=r[1]
16    Rowid          1     5     0                    0   r[5]= rowid of 1
17    IsNull         5     25    0                    0   if r[5]==NULL goto 25
18    String8        0     6     0     table          0   r[6]='table'
19    String8        0     7     0     users          0   r[7]='users'
20    String8        0     8     0     users          0   r[8]='users'
21    Copy           2     9     0                    0   r[9]=r[2]
22    String8        0     10    0     CREATE TABLE users (id INT)  0   r[10]='CREATE TABLE users (id INT)'
23    MakeRecord     6     5     4     BBBDB          0   r[4]=mkrec(r[6..10])
24    Insert         1     4     5                    0   intkey=r[5] data=r[4]
25    SetCookie      0     1     1                    0
26    ParseSchema    0     0     0     tbl_name='users' AND type!='trigger'  0
27    Halt           0     0     0                    0
28    Transaction    0     1     0     0              1   usesStmtJournal=1
29    Goto           0     1     0                    0
```

It might be better to work towards supporting `Insert` and `ParseSchema` and only then work on schema management.

**Comment by penberg** [comment]
@jatin510 There's now work on write path: https://github.com/penberg/limbo/pull/229 When that lands into `main`, we can resume work on schema management.

**Comment by penberg** [comment]
We now have write path in 01ec5f5e6472e0b7f752e1a3e47e560a19f34c42 so work on `CREATE TABLE` can now be implemented!

**Comment by jatin510** [comment]
sure I will look into this !

**Pull request closed without merging**
