### PR TITLE
[ISSUE-257] INSERT to empty tables panic

### PR DESCRIPTION
**Pull request by seonWKim**
### Why does the panic occur 

`page` from `let page = page.borrow()` lives while `write_complete` is running. 

### How to fix 

Ensure that `page` is dropped 

### Related Issue 
https://github.com/penberg/limbo/issues/257

### CODE REVIEW

**Comment by penberg** [comment]
@seonWKim Could you please write a TCL test in `testing/insert.test` for this?

**Review by pereman2 — COMMENTED** [review]
nice! Can we get what was the result before and after changes?

I think you have to remove `database.db` from commit as there are no changes to gen-database.py

**Comment by seonWKim** [comment]
Sure, let me import some of the tcl from sqlite and remove the database.db(maybe add to .gitignore)

**Comment by penberg** [comment]
Hey @seonWKim, the Limbo test is failing, would you be able to look at that? Would love to get this merged.

**Comment by seonWKim** [comment]
Oh, I've been adding some test code and that seems to fail. Let me remove the test code for now and add it in following PR.

**Comment by seonWKim** [comment]
I've temporarily removed the insert test code I've wrote. I'll add it in the following PRs(because I'm currently having trouble setting up my local environment) 

I'll create an issue to prevent myself forgetting ⬇️ 
https://github.com/penberg/limbo/issues/297

**Pull request merged**
