### PR TITLE
Replace unwrap() in PageIO.get() with proper error handling

### PR DESCRIPTION
**Pull request by crrow**
#72

### CODE REVIEW

**Comment by penberg** [comment]
@crrow I improved the pull request subject line a bit. I think we need to also check that the SQLite header has the magic number to ensure we didn't open a file that accidentally looks like a database because some bytes in the page size offset are between 512 and 65536.

**Comment by crrow** [comment]
> @crrow I improved the pull request subject line a bit. I think we need to also check that the SQLite header has the magic number to ensure we didn't open a file that accidentally looks like a database because some bytes in the page size offset are between 512 and 65536.

yeah, check magic number is a more proper way; so what we need to do is verify the first page when open the database file, and assume the following pages are all good? Actually, I'm kind confused why SQLite doesn't exit the process even if he knew the file was invalid.

**Comment by penberg** [comment]
@crrow I think it's just that SQLite opens the database connection _lazily_ until first command is executed, deferring the check. We can do that in our CLI too if we want.

**Comment by penberg** [comment]
@crrow I think the way it works in SQLite is that if theres a parse error on a page, then it just returns a "database corrupt" error on the read. We can do that too.

**Comment by crrow** [comment]
> @crrow I think the way it works in SQLite is that if theres a parse error on a page, then it just returns a "database corrupt" error on the read. We can do that too.

OK, let me try it.

**Pull request merged**
