### PR TITLE
Wal

### PR DESCRIPTION
**Pull request by pereman2**
This pr introduces first iteration of WAL with automatic checkpointing of 1000 pages (not configurable right now).

### CODE REVIEW

**Comment by penberg** [comment]
Hey @pereman2!

I was testing this with an existing SQLite database:

```
penberg@vonneumann limbo % sqlite3 foo.db
SQLite version 3.45.2 2024-03-12 11:06:23
Enter ".help" for usage hints.
sqlite> PRAGMA journal_mode = WAL;
wal
sqlite> CREATE TABLE users (id INT, email TEXT);
sqlite> INSERT INTO users VALUES (1, 'penberg@iki.fi');
sqlite> 
```

but am hitting the following error when I attempt to insert with Limbo:

```
penberg@vonneumann limbo % cargo run foo.db
Limbo v0.0.2
Enter ".help" for usage hints.
limbo> .schema
CREATE TABLE users (id INT, email TEXT);
limbo> SELECT * FROM users;
1|penberg@iki.fi
limbo> INSERT INTO users VALUES (2, 'penberg@gmail.com');
thread 'main' panicked at core/sqlite3_ondisk.rs:502:25:
already borrowed: BorrowMutError
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by pereman2** [comment]
@penberg ahggg thanks for the testing. I should mark this a wip again. I've had to redesign a lot to include fsync as now there is a state machine while doing commit/flush

**Comment by pereman2** [comment]
```
peristocles :: ~/fun/limbo » rm foo.db
peristocles :: ~/fun/limbo » sqlite3 foo.db
SQLite version 3.43.2 2023-10-10 13:08:14
Enter ".help" for usage hints.
sqlite> PRAGMA journal_mode = WAL;
wal
sqlite> CREATE TABLE users (id INT, email TEXT);
sqlite> INSERT INTO users VALUES (1, 'penberg@iki.fi');
sqlite> ^D

    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.36s
     Running `target/debug/limbo foo.db`
syncing
Limbo v0.0.4
Enter ".help" for usage hints.
limbo> .schema
CREATE TABLE users (id INT, email TEXT);
syncing
limbo> select * from users;
1|penberg@iki.fi
syncing
syncing
limbo> INSERT INTO users VALUES (2, 'penberg@gmail.com');
```

@penberg I couldn't reproduce it

**Comment by pereman2** [comment]
I will fix linux IO uring stuff tomorrow once I get access to my linux pc

**Pull request merged**
